---
- name: Check agonek user
  community.routeros.command:
    commands:
      - /user print count-only where name=agonek
  register: agonek_user_check
  changed_when: false

- name: Create agonek user
  community.routeros.command:
    commands:
      - /user add name=agonek group=full password=123456
  when: agonek_user_check.stdout[0] | int == 0
  no_log: true

- name: Change password for admin user
  community.routeros.command:
    commands:
      - /user set admin password=******
